openapi: 3.0.3
info:
  title: Cocktail and ingredient API
  version: 0.0.1

servers:
  - url: http://localhost:8080/api
    description: Local development server

tags:
  - name: 'ingredients'
    description: 'Ingredient Operations'
  - name: 'cocktails'
    description: 'Cocktail Operations'
  - name: 'users'
    description: 'User Operations'
  - name: 'admin'
    description: 'Administrative Operations'
  - name: 'moderation'
    description: 'Moderation Operations'

paths:
  /users/info:
    get:
      security:
        - oauth2:
            - openid
      operationId: getUserInfo
      summary: Get information about the currently logged in user
      tags:
        - users
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /users/info/{id}:
    parameters:
      - $ref: '#/components/parameters/uuidParam'
    get:
      operationId: getProfile
      summary: Get a user's profile information
      tags:
        - users
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /users/nick:
    post:
      security:
        - oauth2:
            - openid
      operationId: setNick
      summary: Set the current user's nickname
      tags:
        - users
      responses:
        204:
          description: Success
        409:
          description: Name is taken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: The nickname to set
              example: "Jim"
  /ingredients:
    get:
      operationId: getIngredients
      summary: Get all ingredients
      tags:
        - ingredients
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalizedIngredient'
    post:
      security:
        - oauth2:
            - openid
      operationId: createIngredient
      summary: Create a new ingredient in the database
      tags:
        - ingredients
      requestBody:
        description: The ingredient to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIngredient'
      responses:
        201:
          description: Retrieve the created ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: An URI pointing at the resource that was just created
        422:
          description: The ingredient was somehow malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /ingredients/{id}:
    parameters:
      - $ref: '#/components/parameters/uuidParam'
    get:
      operationId: getIngredientById
      summary: Get a single ingredient by its ID
      tags:
        - ingredients
      responses:
        200:
          description: Found ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        404:
          description: Ingredient not found
    post:
      security:
        - oauth2:
            - openid
      operationId: updateIngredient
      summary: Update the ingredient with the specified ID
      tags:
        - ingredients
      requestBody:
        description: The ingredient data to update with
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIngredient'
      responses:
        200:
          description: Updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        422:
          description: The ingredient was somehow malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        404:
          description: Ingredient not found
    delete:
      security:
        - oauth2:
            - openid
      operationId: deleteIngredient
      summary: Delete the specified ingredient
      tags:
        - ingredients
      responses:
        204:
          description: Deleted successfully
        404:
          description: Ingredient not found
  /ingredients/admin/create:
    post:
      security:
        - oauth2:
            - openid
      operationId: adminCreateIngredient
      summary: Create an ingredient that is directly public for use by everyone
      tags:
        - ingredients
        - admin
      requestBody:
        description: The ingredient to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIngredient'
      responses:
        201:
          description: Retrieve the created ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: An URI pointing at the resource that was just created
        422:
          description: The ingredient was somehow malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /ingredients/admin/publish/{id}:
    parameters:
      - $ref: '#/components/parameters/uuidParam'
    post:
      security:
        - oauth2:
            - openid
      operationId: setIngredientPublicStatus
      summary: Make an ingredient public (or revoke its public status)
      tags:
        - ingredients
        - admin
      requestBody:
        description: Whether or not to make the ingredient public
        required: true
        content:
          application/json:
            schema:
              type: boolean
      responses:
        204:
          description: Status set successfully
        404:
          description: Ingredient not found
  /ingredients/submit/{id}:
    parameters:
      - $ref: '#/components/parameters/uuidParam'
    get:
      security:
        - oauth2:
            - openid
      operationId: submitIngredient
      summary: Submit an ingredient to moderation in order to make it public
      tags:
        - ingredients
      responses:
        204:
          description: Success
        404:
          description: Ingredient not found
  /ingredients/types:
    get:
      operationId: getIngredientTypes
      summary: Get a list of ingredient types on the server
      tags:
        - ingredients
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalizedIngredientType'
  /ingredients/types/{id}:
    parameters:
      - $ref: '#/components/parameters/uuidParam'
    get:
      operationId: getIngredientTypeById
      summary: Get an ingredient type by its ID
      tags:
        - ingredients
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientType'
        404:
          description: Ingredient Type not found
  /search:
    get:
      operationId: search
      summary: Search for ingredients and cocktails
      tags:
        - ingredients
        - cocktails
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
            example: rum
          description: The term to search for
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'
  /moderation/ingredients/queue/:
    get:
      security:
        - oauth2:
            - openid
      operationId: getIngredientQueue
      summary: Get the moderation queue for ingredients
      tags:
        - ingredients
        - moderation
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalizedIngredient'
  /moderation/ingredients/{id}:
    post:
      security:
        - oauth2:
            - openid
      operationId: moderateIngredient
      summary: Handle the moderation status of an ingredient
      tags:
        - ingredients
        - moderation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Moderation'
      responses:
        204:
          description: Status set successfully
        400:
          description: Invalid moderation status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  parameters:
    uuidParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"

  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            openid: Default OpenID scope
          authorizationUrl: https://dev-991339.okta.com/oauth2/default/v1/authorize

  schemas:
    LocalizedIngredientType:
      description: An ingredient type in a single language
      type: object
      required:
        - type
        - id
        - language
      properties:
        id:
          type: string
          format: uuid
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
        language:
          type: string
          example: de
        type:
          type: string
          example: Starker Alkohol
    LocalizedIngredient:
      description: An ingredient in a single language
      type: object
      required:
        - type
        - language
        - id
        - description
        - name
      properties:
        id:
          type: string
          format: uuid
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
        type:
          $ref: '#/components/schemas/LocalizedIngredientType'
        language:
          type: string
          example: de
        name:
          type: string
          example: Weißer Rum
        description:
          type: string
          example: Ein hochprozentiges Destillat aus Zuckerrohr
    IngredientType:
      description: An ingredient type, with all languages
      type: object
      required:
        - id
        - names
      properties:
        id:
          type: string
          format: uuid
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
        names:
          type: array
          items:
            $ref: '#/components/schemas/TranslatedString'
    Ingredient:
      description: An ingredient, with all languages
      type: object
      required:
        - type
        - names
        - id
        - descriptions
        - published
      properties:
        id:
          type: string
          format: uuid
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
        type:
          $ref: '#/components/schemas/IngredientType'
        names:
          type: array
          items:
            $ref: '#/components/schemas/TranslatedString'
        descriptions:
          type: array
          items:
            $ref: '#/components/schemas/TranslatedString'
        owner:
          $ref: '#/components/schemas/UserInfo'
        published:
          type: boolean
    CreateIngredient:
      description: An ingredient for creation on the server
      type: object
      required:
        - descriptions
        - names
        - typeId
      properties:
        typeId:
          type: string
          format: uuid
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
        names:
          type: array
          items:
            $ref: '#/components/schemas/TranslatedString'
        descriptions:
          type: array
          items:
            $ref: '#/components/schemas/TranslatedString'
    TranslatedString:
      description: A translated string
      type: object
      required:
        - language
        - translation
      properties:
        language:
          type: string
          example: de
        translation:
          type: string
          example: Limettensaft
    SearchResult:
      description: A result of a search for cocktails and ingredients
      type: object
      required:
        - type
        - id
        - name
        - description
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the resource that was found
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [INGREDIENT, COCKTAIL]
    UserInfo:
      type: object
      required:
        - id
      properties:
        nick:
          type: string
          example: "Jim"
        id:
          type: string
          format: uuid
          example: "d61c2b3a-09e3-4305-8f2b-24079ab52e8d"
    ErrorModel:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
          description: The HTTP status code of the error
        message:
          type: string
          description: A further description of the error
    Moderation:
      type: string
      enum: [ACCEPT, REJECT]
