openapi: 3.0.3
info:
  title: Cocktail and ingredient API
  version: 0.0.1

servers:
  - url: http://localhost:8080/
    description: Local development server

tags:
  - name: 'ingredients'
    description: 'Ingredient Operations'
  - name: 'cocktails'
    description: 'Cocktail Operations'

paths:
  /ingredients/{id}:
    get:
      operationId: getIngredientById
      summary: Get a single ingredient by its ID
      tags:
        - ingredients
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully received ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIngredient'

components:
  schemas:
    GetIngredient:
      required:
        - type
        - locale
        - id
        - name
        - description
        - typeId
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        locale:
          type: string
          example: en
        type:
          type: string
          example: Hard Liquor
        typeId:
          type: integer
          format: int64
          example: 5
        name:
          type: string
          example: White rum
        description:
          type: string
          example: A high proof spirit made from sugar cane
