openapi: 3.0.3
info:
  title: Cocktail and ingredient API
  version: 0.0.1

servers:
  - url: http://localhost:8080/
    description: Local development server

tags:
  - name: 'ingredients'
    description: 'Ingredient Operations'
  - name: 'cocktails'
    description: 'Cocktail Operations'
  - name: 'locales'
    description: 'Locale Operations'

paths:
  /ingredients/{id}:
    get:
      operationId: getIngredientById
      summary: Get a single ingredient by its ID
      tags:
        - ingredients
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully received ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIngredient'
        404:
          description: Ingredient not found
  /ingredients:
    post:
      operationId: createNewIngredient
      summary: Create a new ingredient
      tags:
        - ingredients
      requestBody:
        required: true
        description: The ingredient to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIngredient'
      responses:
        200:
          description: The created ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIngredient'
        400:
          description: The ingredient was invalid
  /ingredients/types:
    get:
      operationId: getIngredientTypes
      summary: Get the available ingredient types
      tags:
        - ingredients
      responses:
        200:
          description: A list of ingredient types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IngredientType'
  /locales:
    get:
      operationId: getLocales
      summary: Get the server's list of supported locales
      tags:
        - locales
      responses:
        200:
          description: A list of locales supported by the server
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Locale'
components:
  schemas:
    CreateIngredient:
      type: object
      required:
        - typeId
        - data
      properties:
        typeId:
          type: integer
          format: int64
          example: 10
        data:
          type: array
          items:
            $ref: '#/components/schemas/IngredientData'
          minItems: 1
    IngredientData:
      type: object
      required:
        - description
        - name
        - localeId
      properties:
        localeId:
          type: integer
          format: int64
          example: 5
        name:
          type: string
          example: Bourbon
        description:
          type: string
          example: An american whiskey
    GetIngredient:
      required:
        - type
        - language
        - country
        - id
        - name
        - description
        - typeId
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
          description: The database ID of the locale
        language:
          type: string
          example: de
          minLength: 2
          maxLength: 2
          description: A 2-letter language designator so that a language-country tuple like de-DE can be formed
        country:
          type: string
          example: DE
          minLength: 2
          maxLength: 2
          description: A 2-letter region designator so that a language-country tuple like de-DE can be formed
        type:
          type: string
          example: Hard Liquor
        typeId:
          type: integer
          format: int64
          example: 5
        name:
          type: string
          example: White rum
        description:
          type: string
          example: A high proof spirit made from sugar cane
    Locale:
      type: object
      required:
        - name
        - language
        - country
        - localizedName
      properties:
        language:
          type: string
          example: de
          minLength: 2
          maxLength: 2
          description: A 2-letter language designator so that a language-country tuple like de-DE can be formed
        country:
          type: string
          example: DE
          minLength: 2
          maxLength: 2
          description: A 2-letter region designator so that a language-country tuple like de-DE can be formed
        name:
          type: string
          example: German (Germany)
        localizedName:
          type: string
          example: Deutsch (Deutschland)
        flagEmoji:
          type: string
    IngredientType:
      type: object
      required:
        - id
        - names
      properties:
        id:
          type: integer
          format: int64
          example: 1337
        names:
          type: array
          items:
            $ref: '#/components/schemas/IngredientTypeName'
          minItems: 1
    IngredientTypeName:
      type: object
      required:
        - name
        - language
        - country
      properties:
        language:
          type: string
          example: de
          minLength: 2
          maxLength: 2
          description: A 2-letter language designator so that a language-country tuple like de-DE can be formed
        country:
          type: string
          example: DE
          minLength: 2
          maxLength: 2
          description: A 2-letter region designator so that a language-country tuple like de-DE can be formed
        name:
          type: string
          example: Hard Liquor
