on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        run: gradle publish
        env:
          MAVEN_USERNAME: ${{ env.GITHUB_ACTOR }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

